### ISSUE TITLE
SIMPLE_IDENTIFIER is not assigned to import symbols and aliases

### ISSUE THREAD

**Issue by EgorBu** [bblfsh/python-driver#62] opened 2017-08-09 16:41 UTC
Hi,
I was playing with UASTs and found some bug (as I think):
minimal reproducible example:
```
from os import path
import sys

import numpy as np
```
All SIMPLE_IDENTIFIERS: `{'path': 1, 'numpy': 1, 'sys': 1}` - as we can see - `np` and `os` are missed.

Some helper code to debug:
```
from collections import Counter

from ast2vec.bblfsh_roles import SIMPLE_IDENTIFIER
from ast2vec.repo2.base import Repo2Base


class Repo2IdModel:
    NAME = "Repo2IdModel"


class Repo2IdCounter(Repo2Base):
    """
    Print all SIMPLE_IDENTIFIERs (and counters) from repository
    """
    MODEL_CLASS = Repo2IdModel

    def collect_id_cnt(self, root, id_cnt):
        for ch in root.children:
            if SIMPLE_IDENTIFIER in ch.roles:
                id_cnt[ch.token] += 1
            self.collect_id_cnt(ch, id_cnt)

    def convert_uasts(self, file_uast_generator):
        for file_uast in file_uast_generator:
            print("-" * 20 + " " + str(file_uast.filepath))
            id_cnt = Counter()
            self.collect_id_cnt(file_uast.response.uast, id_cnt)
            print(id_cnt)


if __name__ == "__main__":
    repo = "test/imports/"
    c2v = Repo2IdCounter(linguist="path/to/enry", bblfsh_endpoint="0.0.0.0:9432")
    c2v.convert_repository(repo)
```

**Comment by juanjux** [comment] 2017-08-09 17:04
Both should be easy to fix. I'll take a look tomorrow.

**Comment by EgorBu** [comment] 2017-08-09 20:32
[role vis](https://github.com/EgorBu/uast_playground) - hope that it may help you to debug roles in future

**Comment by EgorBu** [comment] 2017-08-10 09:13
![screenshot from 2017-08-10 11-02-10](https://user-images.githubusercontent.com/2606702/29163053-8c624b94-7dbb-11e7-9e30-60cb63135e7f.png)
Command to reproduce:
`python3 -m uast_playground repo2id_str -r test_data/exp2 `
Additional experiments:
1) wrong start and end positions of tokens (token has more than 1 line, overlaps, wrong length, etc)
2) empty SIMPLE_IDENTIFIER
`!Wrong length of token '' (expected 0 - 0 + 1 == 0)!!Wrong length of token '' (expected 0 - 0 + 1 == 0)!`
3) decorators and function definitions have the same start line
4) arguments to functions are not SIMPLE_IDENTIFIERS (but type for argument is SIMPLE_IDENTIFIER)

**Comment by juanjux** [comment] 2017-08-10 09:34
Please open other issues for the other problems.

**Comment by juanjux** [comment] 2017-08-10 09:35
About 1: the token of a function is the name, but the start and ending positions are the ones of the function itself with body and all, not the token.

**Comment by juanjux** [comment] 2017-08-10 09:40
About 4:

Function arguments have the role `FunctionDeclarationArgumentName`. I'm not sure if `SimpleIdentifier` is needed here since it would be redundant.

**Comment by juanjux** [comment] 2017-08-10 09:51
Back to the original issue, I've already fixed the `os` not having `SimpleIdentifier`, but the `np` problem is going to be harder since in the native AST both the `numpy` and `np` are inside the same node, with the name (that we take in this case as token) being `numpy`. I'll try to find some workaround but I'm not sure it can be done with the current version of the SDK (we can promote lists of dictionaries to their own nodes, but not strings, I think).

**Comment by juanjux** [comment] 2017-08-10 11:01
I'm implementing a feature in the SDK that should fix the second problem; we already have one to optionally promote object properties with list values to child nodes, this one will promote string properties to nodes with the key as node type and the value as token.

**Comment by EgorBu** [comment] 2017-08-10 12:27
what about empty SIMPLE_IDENTIFIERs - do you have an idea what it is?

**Comment by juanjux** [comment] 2017-08-10 12:45
Write a as small as possible code example that produces that, please.

**Comment by juanjux** [comment] 2017-08-10 13:29
Should be fixed by bblfsh/sdk/pull/161 and #64 when merged.

**Comment by EgorBu** [comment] 2017-08-10 13:33
try this one
```


class Repo2nBOW(Repo2Base):
    @property
    def id2vec(self):
        return self._id2vec












```
it gives:
```
egor@egor-sourced:~/workspace/uast_playground$ python3 -m uast_playground repo2id_str -r test_data/exp3 --linguist ~/workspace/ast2vec/enry
-------------------- b'test_data/exp3/nbow.py'


class Repo2nBOW(Repo2Base):!Wrong length of token 'Repo2nBOW' (expected 27 - 7 + 1 == 9)!!token 'Repo2nBOW' start & end line: 2, 5!
    @property!Wrong length of token 'id2vec' (expected 27 - 5 + 1 == 6)!!token 'id2vec' start & end line: 3, 5!
    def id2vec(self):
        return self._id2vec











!Wrong length of token '' (expected 0 - 0 + 1 == 0)!
```

**Comment by EgorBu** [comment] 2017-08-10 13:34
BTW:
```
roles: CALL
          roles: SIMPLE_IDENTIFIER
          roles: 141
```
why doesn't role `141` have name?

**Comment by juanjux** [comment] 2017-08-10 13:54
For the snippet the position of the second `_id2vec` have an offset of 0, which is wrong, I'll open another issue: https://github.com/bblfsh/python-driver/issues/65

**Comment by juanjux** [comment] 2017-08-10 13:55
How do you get that role 141? I can't reproduce it in the snippet you just published.

**Comment by EgorBu** [comment] 2017-08-10 13:56
Just used bblfsh client)
`python3 -m bblfsh -f test_data/exp3/ex.py`

**Comment by juanjux** [comment] 2017-08-10 14:23
`ex.py` is the code in the first message or the snippet you just published?

**Comment by juanjux** [comment] 2017-08-10 14:47
Since the PRs fixing the import roles are merged and the other problems have their issues (#65, bblfsh/client-python/issues/21) I'm closing this one.

**Closed by juanjux** 2017-08-10 14:47 UTC
Labels: bug

**Comment by EgorBu** [comment] 2017-08-10 14:52
About empty SIMPLE_IDENTIFIER - I print this node when node.token == "" and roles have SIMPLE_IDENTIFIER
```
internal_type: "FunctionDef.decorator_list"
properties {
  key: "promotedPropertyList"
  value: "true"
}
children {
  internal_type: "Name"
  properties {
    key: "ctx"
    value: "Load"
  }
  token: "property"
  start_position {
    line: 4
    col: 6
  }
  end_position {
    line: 4
    col: 13
  }
  roles: SIMPLE_IDENTIFIER
  roles: EXPRESSION
}
roles: CALL
roles: SIMPLE_IDENTIFIER
roles: 141
```

**Comment by juanjux** [comment] 2017-08-10 15:16
The empty `SIMPLE_IDENTIFIER` was because that role was added to `decorator_list` that is a grouping node and thus shouldn't have identifiers. Will be fixed on the next update of the Python driver.
