### ISSUE TITLE
SIMPLE_IDENTIFIER is assigned wrongly in `with` statement

### ISSUE THREAD

**Issue by EgorBu** [bblfsh/python-driver#76] opened 2017-08-15 16:25 UTC
Hi,
ex:
```
with open(os.path.join(args.output, "row_vocab.txt"), "w") as out:
    out.write('\n'.join(chosen_words))
```
and UAST containes node with emty token, wrong position (0,0):
```
internal_type: "With.items"
properties {
  key: "promotedPropertyList"
  value: "true"
}
children {
  internal_type: "withitem"
  children {
    internal_type: "Name"
    properties {
      key: "ctx"
      value: "Load"
    }
    properties {
      key: "internalRole"
      value: "context_expr"
    }
    token: "a"
    start_position {
      offset: 5
      line: 1
      col: 6
    }
    end_position {
      offset: 5
      line: 1
      col: 6
    }
    roles: SIMPLE_IDENTIFIER
    roles: EXPRESSION
  }
  children {
    internal_type: "Name"
    properties {
      key: "ctx"
      value: "Store"
    }
    properties {
      key: "internalRole"
      value: "optional_vars"
    }
    token: "b"
    start_position {
      offset: 10
      line: 1
      col: 11
    }
    end_position {
      offset: 10
      line: 1
      col: 11
    }
    roles: SIMPLE_IDENTIFIER
    roles: EXPRESSION
  }
  start_position {
    line: 1
    col: 1
  }
  end_position {
    offset: 10
    line: 1
    col: 11
  }
  roles: SIMPLE_IDENTIFIER
  roles: INCOMPLETE
}
roles: SIMPLE_IDENTIFIER
roles: EXPRESSION
roles: INCOMPLETE
```

**Comment by juanjux** [comment] 2017-08-15 17:03
With.items is a grouping node, so it won't provide any token, just like arguments and other. The native AST also doesn't provide any positions but I guess that could be done adding it to the special cases that take the position of the last element.

**Comment by abeaumont** [comment] 2017-08-17 10:43
Depends on https://github.com/bblfsh/sdk/issues/163

**Comment by juanjux** [comment] 2017-09-12 12:27
I can't reproduce this problem with the last version (v0.8.0) so it was probably fixed with some changes in the last rework, but please note that the UAST provided doesn't match the code in the example and actually all nodes with a textual representation have a token in the provided UAST (except `With.items` that is a "virtual" grouping node and thus doesn't have a role).

I'll close but if you can reproduce this problem with the latest version please comment and I'll reopen.

**Closed by juanjux** 2017-09-12 12:27 UTC
