### ISSUE TITLE
SIMPLE_IDENTIFIER  is not assigned in exception

### ISSUE THREAD

**Issue by EgorBu** [bblfsh/python-driver#75] opened 2017-08-15 16:07 UTC
Hi
Ex:
```
def a():
    env = None
    try:
        something()
    except Exception as e:
        print("Something wrong")
        raise e from None
```
and `e` is not SIMPLE_IDENTIFIER.
Vis:
![selection_007](https://user-images.githubusercontent.com/2606702/29324512-96bbd448-81e4-11e7-96af-0536ce87e782.png)

**Comment by abeaumont** [comment] 2017-08-16 08:55
Thanks for the report @EgorBu. Please note that you can use GH's markdown syntax highlighting instead of attaching an image of the code. Could you attach the generated UAST instead and indicate which part you think is wrong?

**Comment by EgorBu** [comment] 2017-08-16 10:52
I modified code a bit to make it easy to search by grep:
```
# ../ast2vec/ast2vec/cloning.py
def a():
    env = None
    try:
        something()
    except Exception as missing_e:
        print("Something wrong")
        raise missing_e from None
```
UAST:
```
egor@egor-sourced:~/workspace/uast_playground$ python3 -m bblfsh -f test_data/python_driver_issue75/ex.py 
uast {
  internal_type: "Module"
  children {
    internal_type: "FunctionDef"
    properties {
      key: "internalRole"
      value: "body"
    }
    properties {
      key: "returns"
      value: "<nil>"
    }
    children {
      internal_type: "arguments"
      properties {
        key: "internalRole"
        value: "args"
      }
      properties {
        key: "kwarg"
        value: "<nil>"
      }
      properties {
        key: "vararg"
        value: "<nil>"
      }
      start_position {
        offset: 32
        line: 2
        col: 1
      }
      roles: FUNCTION_DECLARATION_ARGUMENT
      roles: INCOMPLETE
    }
    children {
      internal_type: "FunctionDef.body"
      properties {
        key: "promotedPropertyList"
        value: "true"
      }
      children {
        internal_type: "Assign"
        children {
          internal_type: "Name"
          properties {
            key: "ctx"
            value: "Store"
          }
          properties {
            key: "internalRole"
            value: "targets"
          }
          children {
            internal_type: "PreviousNoops"
            properties {
              key: "internalRole"
              value: "noops_previous"
            }
            children {
              internal_type: "NoopLine"
              properties {
                key: "internalRole"
                value: "lines"
              }
              token: "# ../ast2vec/ast2vec/cloning.py\n"
              start_position {
                line: 1
                col: 1
              }
              roles: COMMENT
            }
            start_position {
              line: 1
              col: 1
            }
            end_position {
              offset: 30
              line: 1
              col: 31
            }
            roles: WHITESPACE
          }
          token: "env"
          start_position {
            offset: 45
            line: 3
            col: 5
          }
          end_position {
            offset: 47
            line: 3
            col: 7
          }
          roles: ASSIGNMENT_VARIABLE
          roles: SIMPLE_IDENTIFIER
          roles: EXPRESSION
        }
        children {
          internal_type: "NoneLiteral"
          properties {
            key: "internalRole"
            value: "value"
          }
          token: "<nil>"
          start_position {
            offset: 51
            line: 3
            col: 11
          }
          end_position {
            offset: 54
            line: 3
            col: 14
          }
          roles: NULL_LITERAL
          roles: EXPRESSION
          roles: ASSIGNMENT_VALUE
        }
        start_position {
          offset: 45
          line: 3
          col: 5
        }
        end_position {
          offset: 54
          line: 3
          col: 14
        }
        roles: ASSIGNMENT
        roles: EXPRESSION
      }
      children {
        internal_type: "Try"
        children {
          internal_type: "Try.body"
          properties {
            key: "promotedPropertyList"
            value: "true"
          }
          children {
            internal_type: "Expr"
            children {
              internal_type: "Call"
              properties {
                key: "internalRole"
                value: "value"
              }
              children {
                internal_type: "Name"
                properties {
                  key: "ctx"
                  value: "Load"
                }
                properties {
                  key: "internalRole"
                  value: "func"
                }
                token: "something"
                start_position {
                  offset: 73
                  line: 5
                  col: 9
                }
                end_position {
                  offset: 81
                  line: 5
                  col: 17
                }
                roles: CALL
                roles: SIMPLE_IDENTIFIER
                roles: EXPRESSION
              }
              start_position {
                offset: 74
                line: 5
                col: 10
              }
              end_position {
                offset: 81
                line: 5
                col: 17
              }
              roles: CALL
              roles: EXPRESSION
            }
            start_position {
              offset: 73
              line: 5
              col: 9
            }
            end_position {
              offset: 81
              line: 5
              col: 17
            }
            roles: EXPRESSION
          }
          roles: TRY_BODY
        }
        children {
          internal_type: "Try.handlers"
          properties {
            key: "promotedPropertyList"
            value: "true"
          }
          children {
            internal_type: "ExceptHandler"
            children {
              internal_type: "Expr"
              properties {
                key: "internalRole"
                value: "body"
              }
              children {
                internal_type: "Call"
                properties {
                  key: "internalRole"
                  value: "value"
                }
                children {
                  internal_type: "StringLiteral"
                  properties {
                    key: "internalRole"
                    value: "args"
                  }
                  token: "Something wrong"
                  start_position {
                    offset: 134
                    line: 7
                    col: 15
                  }
                  end_position {
                    offset: 150
                    line: 7
                    col: 31
                  }
                  roles: STRING_LITERAL
                  roles: EXPRESSION
                  roles: CALL_POSITIONAL_ARGUMENT
                }
                children {
                  internal_type: "Name"
                  properties {
                    key: "ctx"
                    value: "Load"
                  }
                  properties {
                    key: "internalRole"
                    value: "func"
                  }
                  token: "print"
                  start_position {
                    offset: 128
                    line: 7
                    col: 9
                  }
                  end_position {
                    offset: 132
                    line: 7
                    col: 13
                  }
                  roles: CALL
                  roles: SIMPLE_IDENTIFIER
                  roles: EXPRESSION
                }
                start_position {
                  offset: 129
                  line: 7
                  col: 10
                }
                end_position {
                  offset: 150
                  line: 7
                  col: 31
                }
                roles: CALL
                roles: EXPRESSION
              }
              start_position {
                offset: 128
                line: 7
                col: 9
              }
              end_position {
                offset: 150
                line: 7
                col: 31
              }
              roles: EXPRESSION
            }
            children {
              internal_type: "Raise"
              properties {
                key: "internalRole"
                value: "body"
              }
              children {
                internal_type: "NoneLiteral"
                properties {
                  key: "internalRole"
                  value: "cause"
                }
                token: "<nil>"
                start_position {
                  offset: 182
                  line: 8
                  col: 30
                }
                end_position {
                  offset: 185
                  line: 8
                  col: 33
                }
                roles: NULL_LITERAL
                roles: EXPRESSION
              }
              children {
                internal_type: "Name"
                properties {
                  key: "ctx"
                  value: "Load"
                }
                properties {
                  key: "internalRole"
                  value: "exc"
                }
                token: "missing_e"
                start_position {
                  offset: 167
                  line: 8
                  col: 15
                }
                end_position {
                  offset: 175
                  line: 8
                  col: 23
                }
                roles: SIMPLE_IDENTIFIER
                roles: EXPRESSION
              }
              start_position {
                offset: 161
                line: 8
                col: 9
              }
              end_position {
                offset: 185
                line: 8
                col: 33
              }
              roles: THROW
              roles: STATEMENT
            }
            children {
              internal_type: "Name"
              properties {
                key: "ctx"
                value: "Load"
              }
              properties {
                key: "internalRole"
                value: "type"
              }
              token: "Exception"
              start_position {
                offset: 96
                line: 6
                col: 12
              }
              end_position {
                offset: 104
                line: 6
                col: 20
              }
              roles: SIMPLE_IDENTIFIER
              roles: EXPRESSION
            }
            token: "missing_e"
            start_position {
              offset: 109
              line: 6
              col: 25
            }
            end_position {
              offset: 185
              line: 8
              col: 33
            }
            roles: TRY_CATCH
            roles: STATEMENT
          }
          roles: TRY_CATCH
        }
        start_position {
          offset: 60
          line: 4
          col: 5
        }
        end_position {
          offset: 185
          line: 8
          col: 33
        }
        roles: TRY
        roles: STATEMENT
      }
      roles: FUNCTION_DECLARATION_BODY
    }
    token: "a"
    start_position {
      offset: 36
      line: 2
      col: 5
    }
    end_position {
      offset: 185
      line: 8
      col: 33
    }
    roles: FUNCTION_DECLARATION
    roles: FUNCTION_DECLARATION_NAME
    roles: SIMPLE_IDENTIFIER
  }
  start_position {
    line: 1
    col: 1
  }
  end_position {
    offset: 185
    line: 8
    col: 33
  }
  roles: FILE
}
```

Problem node:
```
token: "missing_e"
            start_position {
              offset: 109
              line: 6
              col: 25
            }
            end_position {
              offset: 185
              line: 8
              col: 33
            }
            roles: TRY_CATCH
            roles: STATEMENT
```

**Comment by abeaumont** [comment] 2017-08-17 10:42
The problem is not with the Roles but with the token. This node is a parent of the "missing_e" identifier and should probably not have a token.
It's a duplicate of #70

**Closed** 2017-08-22 12:47 UTC
Labels: bug, duplicate
