### ISSUE TITLE
Node positions not being according with specs

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/python-driver#30] opened 2017-06-27 15:10 UTC
It is not retrieved `start_position.offset` field nor `end_position` as documented by https://doc.bblf.sh/uast/specification.html
All token positions on the same line has the same `start_position`
> _[...] it is guaranteed that nodes in a UAST either have no position attached or they have a position with valid offset, line and col. [...]_
> _End position, if present in a token node, is the position of the last character of the token in the original source code._

![pasted image at 2017_06_27 08_58 am](https://user-images.githubusercontent.com/2437584/27594607-853e04b2-5b5a-11e7-9279-b7f7f9451068.png)

example:
```
import sys
sys.stdout.write("Hello world!\n")
```
client: [client-python](https://github.com/bblfsh/client-python)
It is retrieved the same positions for second line `sys` and `stdout` Nodes
```
start_position {
    line: 2
    col: 1
}
```

**Comment by abeaumont** [comment] 2017-06-27 15:25
As commented in https://github.com/bblfsh/java-driver/issues/27, it's probably a serialization problem

**Comment by juanjux** [comment] 2017-06-27 16:15
Unfortunately, in this case it's given like that from the Python native AST of attributed calls:

```python
from ast import parse
root = parse("sys.stdout.write()")
stdout_node = root.body[0].value.func.value
sys_node = root.body[0].value.func.value.value
# wont fail:
assert(stdout_node.col_offset == sys_node.col_offset)
```
So the issue is really a Python one.

One possible solution for this case would be to extend the synchronized tokenizer that I use for adding the comments and noops to the UAST to also update the correct positions. But that would be a workaround for an external issue, so I'm changing this to feature.

**Comment by juanjux** [comment] 2017-06-27 16:38
Ok, so it's a bug.

**Comment by juanjux** [comment] 2017-06-27 16:59
Looks like their concept of col_offset for attributes is a little different than ours:

https://bugs.python.org/issue21295

> ast.Attribute node actually means "the atribute of something", ie. the node includes this "something" as subnode

So the best solution will probably be to extend the sinchronized tokenizer for this (and maybe we can also get the end_position too that way, trough I'm not sure if that's possible without reimplementing a full python parser).

**Comment by smola** [comment] 2017-06-28 07:28
See my comment here for clarification on end position, as well as possible fix for the offset (`FillOffsetFromLineCol`).
https://github.com/bblfsh/java-driver/issues/27#issuecomment-311579633

**Comment by juanjux** [comment] 2017-06-28 07:35
@smola, will try it, thanks.

**Comment by juanjux** [comment] 2017-07-03 15:00
Starting to work on this. It'll probably take a while so I'll keep this subtask list updated:

- [ ] Use the SDK, if possible, to calculate the offset.
- [ ] Modify the synchronized tokenizer to also add (or correct) the startposition of nodes.
- [ ] Same but for adding the endposition. This will only be implemented as part of this issue if it can't be done quickly; else it'll have to be planned for another sprint, if needed.

**Comment by juanjux** [comment] 2017-07-04 07:34
Since after the checking the specs endposition is not mandatory I'll open a feature request for it and remove it from this bug task list.

**Comment by juanjux** [comment] 2017-07-06 17:18
PR #37 should fix two of the three problems related with this issue (offsets at 0 and some columns at 0 too). Next PR should fix the remaining issue (questionable positions given by the Python native AST module).

**Comment by juanjux** [comment] 2017-07-12 12:03
PR bblfsh/python-pydetector/pull/9 should fix the third problem when merged so this could be closed. I've also seen an option for implementing #33 for most, if not all, Python nodes; I'll work on that soon.

**Closed** 2017-07-12 17:22 UTC
Labels: bug
