### ISSUE TITLE
Server "hanging". Empty code received, returning empty UAST

### ISSUE THREAD

**Issue by zurk** [bblfsh/python-driver#98] opened 2017-09-22 16:10 UTC
Related to this issue https://github.com/bblfsh/server/issues/101 (actually problem was no in the server but in python-driver). I have kind of the same symptoms with a new driver. At some moment the server logs:
```
time="2017-09-22T15:41:39Z" level=debug msg="Empty code received, returning empty UAST"
```
And then nothing, but my program actually continues to send queries. At some moment  (~after 30sec) server logs
```
time="2017-09-22T15:42:11Z" level=debug msg="driver exited without error"
```
and then you can actually continue parsing.

I couldn't find the file which breaks everything, and also if I run 1 thread for queries, everything seems to be fine. 

Code to reproduce: 
https://gist.github.com/zurk/2d9e786e6577ebe60e963091c13b4ecd

[files.txt](https://github.com/bblfsh/python-driver/files/1325116/files.txt)
they are on `science-3`. Can download it and attach if you want.

**Comment by juanjux** [comment] 2017-10-04 08:03
Hi again @zurk, could you try again with the latest versions? @mcuadros did several fixes for paralellism in the SDK and server along with better debugging and error reporting.

**Comment by juanjux** [comment] 2017-10-05 10:51
I'll preventively closing this since I couldn't reproduce. Please feel free to reopen if this happens again.

**Closed by juanjux** 2017-10-05 10:51 UTC
Labels: bug
