### ISSUE TITLE
Errors during installation of drivers

### ISSUE THREAD

**Issue by EgorBu** [bblfsh/python-driver#156] opened 2018-05-21 13:38 UTC
Hi,
During installation of drivers - several of them failed, one is python.
Command below
```
docker run -d --name bblfshd --privileged -p 9432:9432 bblfsh/bblfshd
docker exec -it bblfshd bblfshctl driver install --recommended
```
Here is the log:
```bash
egor@egor-sourced:~/workspace/code-annotation$ docker exec -it bblfshd bblfshctl driver install --recommended
Installing bash language driver from "docker://bblfsh/bash-driver:latest"... Done
Installing go language driver from "docker://bblfsh/go-driver:latest"... Done
Installing ruby language driver from "docker://bblfsh/ruby-driver:latest"... Error
Error, unable to delete whiteout path: lstat /var/lib/bblfshd/tmp/image876882015/usr/lib/ruby/gems/2.4.0/gems/ast-2.4.0/.wh..opq: operation not permitted
Installing javascript language driver from "docker://bblfsh/javascript-driver:latest"... Done
Installing php language driver from "docker://bblfsh/php-driver:latest"... Done
Installing java language driver from "docker://bblfsh/java-driver:latest"... Done
Installing python language driver from "docker://bblfsh/python-driver:latest"... Error
Error, unable to delete whiteout path: lstat /var/lib/bblfshd/tmp/image837347843/usr/lib/python3.6/site-packages/pydetector/.wh..opq: operation not permitted
```

**Comment by juanjux** [comment] 2019-01-14 13:46
Is this still happening? I can't reproduce it.

**Comment by juanjux** [comment] 2019-02-11 17:22
Closing it, feel free to reopen if you can reproduce it with the latest versions.

**Closed by juanjux** 2019-02-11 17:22 UTC
